### ISSUE TITLE
[Feature request]: Incorporate metabolomics and proteomics data

### ISSUE THREAD

**Issue by nctoussaint** [sdsc-ordes/modos-api#91]
### Description

As discussed with the SMOC team, MODOs should be extended to include metabolomics and proteomics data.

Patrick Pedrioli and Nicola Zamboni have provided example data with metadata via a SWITCH drive ORDES provided: 
https://drive.switch.ch/index.php/s/k1Tng5UjjqV6Eqf

### Importance Level

High

**Comment by cmdoret** [comment]
Hey @htmonkey @ppedrioli,

We would love to have your input on this:

**metadata**
* are there exclusive metadata fields between mztab and mztab-m that would warrant a separate class in the schema (example for context: [modos:ReferenceGenome](https://sdsc-ordes.github.io/modos-schema/ReferenceGenome/)) ?
* do you have a list of metadata fields that should be extracted in priority from mztab files for a first prototype? 
* Do you think [modos:DataEntity](https://sdsc-ordes.github.io/modos-schema/DataEntity/) could be extended (i.e. adding fields) to represent mztab, or do you recommend creating a completely separate object?
  + Asking mainly because as far as I can tell a single mztab contains multiple arrays.
  + One solution to this would be to have a grouping type, (DataCollection?) pointing to the individual arrays.

**storage**
* We were thinking of storing the experiment-level metadata as json (in zarr), as we do for genomics, and the actual data in zarr arrays (which allows indexes, random access and compression). Does make sense?

**interaction**

We were thinking about something like 
```shell
modos --endpoint http://s3.example.org add mztab s3://my-bucket/test-object ./exp1.mztab
```
Does that look OK to you?

We would be interested in the kind of "questions" you would then ask to the object. This would help us designing the command line interface, API and metadata schema. Suggestions are welcome.
